import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Stream;

/**
 * Reads the sales input files and creates the requested sales reports.
 *
 * <p>This is the second executable class required by the project. Run
 * {@link GenerateInfoFiles} first, then run this class. The reports are
 * generated in {@code data/output} and the program never requests data from
 * the user.</p>
 *
 * @author Alejandro Anibal Andrade
 * @version 1.0
 */
public class main {

    /** Folder with the files generated by GenerateInfoFiles. */
    private static final Path INPUT_DIRECTORY = Paths.get("data", "input");

    /** Folder where the sales reports are created. */
    private static final Path OUTPUT_DIRECTORY = Paths.get("data", "output");

    /** Input file containing the product catalog. */
    private static final Path PRODUCTS_FILE = INPUT_DIRECTORY.resolve("products.csv");

    /** Input file containing salesperson information. */
    private static final Path SALESMEN_FILE = INPUT_DIRECTORY.resolve("salesmen.csv");

    /** Output report ordered by money collected by every salesperson. */
    private static final Path SALESMEN_REPORT_FILE =
            OUTPUT_DIRECTORY.resolve("salesmen_report.csv");

    /** Output report ordered by quantity sold for every product. */
    private static final Path PRODUCTS_REPORT_FILE =
            OUTPUT_DIRECTORY.resolve("products_report.csv");

    /**
     * Reads the generated input files and creates both required reports.
     *
     * @param args command-line arguments, not used by this program
     */
    public static void main(String[] args) {
        try {
            Map<String, Product> products = readProducts();
            Map<Long, Salesman> salesmen = readSalesmen();
            Map<Long, Long> moneyCollected = createInitialMoneyMap(salesmen);
            Map<String, Integer> quantitiesSold = new HashMap<String, Integer>();

            processSalesFiles(products, salesmen, moneyCollected, quantitiesSold);
            Files.createDirectories(OUTPUT_DIRECTORY);
            createSalesmenReport(salesmen, moneyCollected);
            createProductsReport(products, quantitiesSold);

            System.out.println("Reports generated successfully in: "
                    + OUTPUT_DIRECTORY.toAbsolutePath());
        } catch (IOException | IllegalArgumentException exception) {
            System.err.println("The reports could not be generated: "
                    + exception.getMessage());
        }
    }

    /**
     * Reads the available products from the catalog file.
     *
     * @return products indexed by product id
     * @throws IOException when the file cannot be read
     */
    private static Map<String, Product> readProducts() throws IOException {
        Map<String, Product> products = new HashMap<String, Product>();
        List<String> lines = Files.readAllLines(PRODUCTS_FILE, StandardCharsets.UTF_8);

        for (String line : lines) {
            String[] values = line.split(";", -1);
            if (values.length != 3) {
                throw new IllegalArgumentException("Invalid product record: " + line);
            }

            String id = values[0].trim();
            String name = values[1].trim();
            long price = parsePositiveLong(values[2].trim(), "product price");

            if (id.isEmpty() || name.isEmpty() || products.containsKey(id)) {
                throw new IllegalArgumentException("Inconsistent product record: " + line);
            }
            products.put(id, new Product(id, name, price));
        }
        return products;
    }

    /**
     * Reads the information of all salespeople.
     *
     * @return salespeople indexed by document number
     * @throws IOException when the file cannot be read
     */
    private static Map<Long, Salesman> readSalesmen() throws IOException {
        Map<Long, Salesman> salesmen = new HashMap<Long, Salesman>();
        List<String> lines = Files.readAllLines(SALESMEN_FILE, StandardCharsets.UTF_8);

        for (String line : lines) {
            String[] values = line.split(";", -1);
            if (values.length != 4) {
                throw new IllegalArgumentException("Invalid salesman record: " + line);
            }

            long id = parsePositiveLong(values[1].trim(), "salesman document number");
            String firstName = values[2].trim();
            String lastName = values[3].trim();

            if (firstName.isEmpty() || lastName.isEmpty() || salesmen.containsKey(id)) {
                throw new IllegalArgumentException("Inconsistent salesman record: " + line);
            }
            salesmen.put(id, new Salesman(id, firstName, lastName));
        }
        return salesmen;
    }

    /**
     * Creates an initial zero-value total for every salesperson.
     *
     * @param salesmen salespeople indexed by document number
     * @return map with a money total for every salesperson
     */
    private static Map<Long, Long> createInitialMoneyMap(Map<Long, Salesman> salesmen) {
        Map<Long, Long> moneyCollected = new HashMap<Long, Long>();
        for (Long salesmanId : salesmen.keySet()) {
            moneyCollected.put(salesmanId, 0L);
        }
        return moneyCollected;
    }

    /**
     * Processes every sales file stored in the input directory.
     *
     * @param products products indexed by id
     * @param salesmen salespeople indexed by document number
     * @param moneyCollected accumulated money for every salesperson
     * @param quantitiesSold accumulated units for every product
     * @throws IOException when a sales file cannot be read
     */
    private static void processSalesFiles(Map<String, Product> products,
            Map<Long, Salesman> salesmen, Map<Long, Long> moneyCollected,
            Map<String, Integer> quantitiesSold) throws IOException {
        try (Stream<Path> files = Files.list(INPUT_DIRECTORY)) {
            List<Path> salesFiles = new ArrayList<Path>();
            files.filter(path -> path.getFileName().toString().startsWith("sales_"))
                    .filter(path -> path.getFileName().toString().endsWith(".csv"))
                    .forEach(salesFiles::add);

            if (salesFiles.isEmpty()) {
                throw new IllegalArgumentException("No sales files were found in "
                        + INPUT_DIRECTORY.toAbsolutePath());
            }

            for (Path salesFile : salesFiles) {
                processSalesFile(salesFile, products, salesmen, moneyCollected,
                        quantitiesSold);
            }
        }
    }

    /**
     * Processes the sales recorded in one file.
     *
     * @param salesFile sales file to process
     * @param products products indexed by id
     * @param salesmen salespeople indexed by document number
     * @param moneyCollected accumulated money for every salesperson
     * @param quantitiesSold accumulated units for every product
     * @throws IOException when the file cannot be read
     */
    private static void processSalesFile(Path salesFile, Map<String, Product> products,
            Map<Long, Salesman> salesmen, Map<Long, Long> moneyCollected,
            Map<String, Integer> quantitiesSold) throws IOException {
        List<String> lines = Files.readAllLines(salesFile, StandardCharsets.UTF_8);
        if (lines.size() < 2) {
            throw new IllegalArgumentException("Sales file has no sales: " + salesFile.getFileName());
        }

        String[] salesmanValues = lines.get(0).split(";", -1);
        if (salesmanValues.length != 2) {
            throw new IllegalArgumentException("Invalid salesman header in: "
                    + salesFile.getFileName());
        }

        long salesmanId = parsePositiveLong(salesmanValues[1].trim(), "salesman document number");
        if (!salesmen.containsKey(salesmanId)) {
            throw new IllegalArgumentException("Salesman does not exist in: "
                    + salesFile.getFileName());
        }

        for (int lineIndex = 1; lineIndex < lines.size(); lineIndex++) {
            String[] saleValues = lines.get(lineIndex).split(";", -1);
            if (saleValues.length != 2) {
                throw new IllegalArgumentException("Invalid sale record in: "
                        + salesFile.getFileName());
            }

            String productId = saleValues[0].trim();
            int quantity = parsePositiveInt(saleValues[1].trim(), "quantity sold");
            Product product = products.get(productId);
            if (product == null) {
                throw new IllegalArgumentException("Product does not exist in: "
                        + salesFile.getFileName());
            }

            long saleTotal = product.getPrice() * quantity;
            moneyCollected.put(salesmanId,
                    moneyCollected.get(salesmanId) + saleTotal);
            int currentQuantity = quantitiesSold.containsKey(productId)
                    ? quantitiesSold.get(productId) : 0;
            quantitiesSold.put(productId, currentQuantity + quantity);
        }
    }

    /**
     * Creates the report of salespeople ordered from highest to lowest revenue.
     *
     * @param salesmen salespeople indexed by document number
     * @param moneyCollected accumulated money for every salesperson
     * @throws IOException when the report cannot be written
     */
    private static void createSalesmenReport(Map<Long, Salesman> salesmen,
            Map<Long, Long> moneyCollected) throws IOException {
        List<Salesman> orderedSalesmen = new ArrayList<Salesman>(salesmen.values());
        Collections.sort(orderedSalesmen, new Comparator<Salesman>() {
            @Override
            public int compare(Salesman first, Salesman second) {
                int comparison = Long.compare(moneyCollected.get(second.getId()),
                        moneyCollected.get(first.getId()));
                return comparison != 0 ? comparison
                        : first.getFullName().compareTo(second.getFullName());
            }
        });

        try (BufferedWriter writer = Files.newBufferedWriter(SALESMEN_REPORT_FILE,
                StandardCharsets.UTF_8, StandardOpenOption.CREATE,
                StandardOpenOption.TRUNCATE_EXISTING)) {
            for (Salesman salesman : orderedSalesmen) {
                writer.write(salesman.getFullName() + ";"
                        + moneyCollected.get(salesman.getId()));
                writer.newLine();
            }
        }
    }

    /**
     * Creates the product report ordered by units sold from highest to lowest.
     *
     * <p>Each line has the product name and unit price, as required in the
     * project guide. The ordering is calculated with the quantities sold.</p>
     *
     * @param products products indexed by id
     * @param quantitiesSold accumulated units for every product
     * @throws IOException when the report cannot be written
     */
    private static void createProductsReport(Map<String, Product> products,
            final Map<String, Integer> quantitiesSold) throws IOException {
        List<Product> orderedProducts = new ArrayList<Product>();
        for (String productId : quantitiesSold.keySet()) {
            orderedProducts.add(products.get(productId));
        }

        Collections.sort(orderedProducts, new Comparator<Product>() {
            @Override
            public int compare(Product first, Product second) {
                int firstQuantity = quantitiesSold.get(first.getId());
                int secondQuantity = quantitiesSold.get(second.getId());
                int comparison = Integer.compare(secondQuantity, firstQuantity);
                return comparison != 0 ? comparison
                        : first.getName().compareTo(second.getName());
            }
        });

        try (BufferedWriter writer = Files.newBufferedWriter(PRODUCTS_REPORT_FILE,
                StandardCharsets.UTF_8, StandardOpenOption.CREATE,
                StandardOpenOption.TRUNCATE_EXISTING)) {
            for (Product product : orderedProducts) {
                writer.write(product.getName() + ";" + product.getPrice());
                writer.newLine();
            }
        }
    }

    /**
     * Parses and validates a positive long value.
     *
     * @param value text to parse
     * @param fieldName logical name of the field
     * @return parsed positive value
     */
    private static long parsePositiveLong(String value, String fieldName) {
        try {
            long number = Long.parseLong(value);
            if (number <= 0) {
                throw new IllegalArgumentException(fieldName + " must be positive.");
            }
            return number;
        } catch (NumberFormatException exception) {
            throw new IllegalArgumentException("Invalid " + fieldName + ": " + value);
        }
    }

    /**
     * Parses and validates a positive integer value.
     *
     * @param value text to parse
     * @param fieldName logical name of the field
     * @return parsed positive value
     */
    private static int parsePositiveInt(String value, String fieldName) {
        long number = parsePositiveLong(value, fieldName);
        if (number > Integer.MAX_VALUE) {
            throw new IllegalArgumentException(fieldName + " is too large.");
        }
        return (int) number;
    }

    /** Represents one product from the products file. */
    private static class Product {
        private final String id;
        private final String name;
        private final long price;

        Product(String id, String name, long price) {
            this.id = id;
            this.name = name;
            this.price = price;
        }

        String getId() {
            return id;
        }

        String getName() {
            return name;
        }

        long getPrice() {
            return price;
        }
    }

    /** Represents one salesperson from the information file. */
    private static class Salesman {
        private final long id;
        private final String firstName;
        private final String lastName;

        Salesman(long id, String firstName, String lastName) {
            this.id = id;
            this.firstName = firstName;
            this.lastName = lastName;
        }

        long getId() {
            return id;
        }

        String getFullName() {
            return firstName + " " + lastName;
        }
    }
}
